server:
  port: 82
  error:
    include-message: always
    whitelabel:
      enabled: true
spring:
  application:
    name: audit-service
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/msaudit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 80
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 80
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size : 80
      minimum-idle: 10
      pool-name : MsAuditConnPool
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_class : "com.zaxxer.hikari.hibernate.HikariConnectionProvider"
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
  sql:
    init:
      platform: postgres
config:
  housekeep:
    interval:
      audit: "7 days"
  scheduler:
    audit:
      #doHousekeepAudit: "0 0 4 * * ?" #everyday 4:00:00 a.m.
      doHousekeepAudit: "*/5 * * * * ?" #everyday 5 seconds
  internal:
    api:
      micro:
        path: "/api/audit-service"
      key: 4da85148-6e25-4a2e-9744-382adf1c3e9c
  webclient:
    connectTimeoutMillis: 5000
    responseTimeoutMillis: 5000
    readTimeoutMillis: 5000
    writeTimeoutMillis: 5000
    sslBypass: true
swagger:
  host: "http://localhost:${server.port}"
  contextPath: "${config.internal.api.micro.path}"
springdoc:
  swagger-ui:
    enabled: true
    path: "/index.html"
    doc-expansion: none
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  webjars:
    prefix: ""
