server:
  port: 81
  error:
    include-message: always
    whitelabel:
      enabled: true
spring:
  application:
    name: task-service
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/mstask
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    filters: stat
    maxActive: 80
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 80
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size : 80
      minimum-idle: 10
      pool-name : MsTaskConnPool
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_class : "com.zaxxer.hikari.hibernate.HikariConnectionProvider"
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
  sql:
    init:
      platform: postgres
swagger:
  host: "http://localhost:${server.port}"
  contextPath: "${config.internal.api.micro.path}}"
springdoc:
  swagger-ui:
    enabled: true
    path: "/index.html"
    doc-expansion: none
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  webjars:
    prefix: ""
config:
  webclient:
    connectTimeoutMillis: 5000
    responseTimeoutMillis: 5000
    readTimeoutMillis: 5000
    writeTimeoutMillis: 5000
    sslBypass: true
  internal:
    api:
      micro:
        path: "/api/task-service"
      key: 02b689a8-9e62-4e55-8b24-eebdb27c4eec
integration:
  audit:
    baseUrl: "http://localhost:82"
    url: "${integration.audit.baseUrl}/log/v1/create"
    apiKey: 4da85148-6e25-4a2e-9744-382adf1c3e9c